#!/usr/bin/env bash
set -e

export GIT_DIR=/home/jermarti/shadow-creatures-repo
export GIT_WORK_TREE=/home/jermarti/shadow-creatures

echo "Checking out latest..."
git checkout -f exhibition

echo "Restarting services..."
/home/jermarti/shadow-creatures/scripts/deploy/restart_services.sh

echo "OK"
