#!/usr/bin/env bash
set -e

export GIT_DIR=/home/jermarti/maind-deploy-repo
export GIT_WORK_TREE=/home/jermarti/maind-deploy

echo "Checking out latest..."
git checkout -f main

echo "Restarting services..."
/home/jermarti/maind-deploy/scripts/deploy/restart_services.sh

echo "OK"
